const { Apartment } = require('../models');

const apartmentData = [
  {
    address1: '235 Old Colony Ave',
    city: 'Boston',
    state: 'MA',
    zip: '02127',
    date_added: '2024-01-15 9:00:00',
    rent: '$4500',
    beds: '2',
    baths: '2',
    rating: '4',
    notes: 'New kitchen and bethrooms',
    link: 'https://www.apartments.com/south-standard-boston-ma/j5ve2k4/',
    user_id: '1',
    appartment_collection_id: '1'
  },
  {
    address1: '1211 Dorchester Ave',
    city: 'Boston',
    state: 'MA',
    zip: '02125',
    date_added: '2024-01-15 10:00:00',
    rent: '$3740',
    beds: '2',
    baths: '2',
    rating: '5',
    notes: 'Close to public transit',
    link: 'https://www.apartments.com/dot-block-boston-ma/33mrbcf/',
    user_id: '1',
    appartment_collection_id: '1'
  },
  {
    address1: '1335 Boylston St',
    city: 'Boston',
    state: 'MA',
    zip: '02215',
    date_added: '2024-01-15 11:00:00',
    rent: '$6000',
    beds: '2',
    baths: '2',
    rating: '3',
    notes: 'Expensive, but very nice and great area',
    link: 'https://www.apartments.com/van-ness-boston-ma/3ew3tge/',
    user_id: '1',
    appartment_collection_id: '1'
  },
  {
    address1: '201 S Huntington Ave',
    city: 'Boston',
    state: 'MA',
    zip: '02130',
    date_added: '2024-01-15 12:00:00',
    rent: '$4300',
    beds: '2',
    baths: '2',
    rating: '5',
    notes: 'Pet friendly and includes a gym',
    link: 'https://www.apartments.com/the-brynx-boston-ma/xyjltwm/',
    user_id: '1',
    appartment_collection_id: '1'
  },
  {
    address1: 'One Leighton St',
    city: 'Cambridge',
    state: 'MA',
    zip: '02141',
    date_added: '2024-01-16 17:00:00',
    rent: '$4170',
    beds: '2',
    baths: '2',
    rating: '3',
    notes: 'Longer commute to work',
    link: 'https://www.apartments.com/elevate-cambridge-ma/rn5dm12/',
    user_id: '1',
    appartment_collection_id: '1'
  },
  {
    address1: '901 N 9th St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19123',
    date_added: '2024-01-12 17:00:00',
    rent: '$1895',
    beds: '1',
    baths: '1',
    rating: '5',
    notes: 'New bulding, nice area',
    link: 'https://www.apartments.com/the-poplar-philadelphia-pa/016njq2/',
    user_id: '1',
    apartment_collection_id: '2'
  },
  {
    address1: '7715 Crittenden St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19118',
    date_added: '2024-01-12 17:25:00',
    rent: '$1450',
    beds: '1',
    baths: '1',
    rating: '4',
    notes: 'Great floor plan',
    link: 'https://www.apartments.com/chestnut-hill-village-philadelphia-pa/4sbjxeh/',
    user_id: '1',
    appartment_collection_id: '2'
  },
  {
    address1: '3701 Chestnut St',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19104',
    date_added: '2024-01-12 18:45:00',
    rent: '$750',
    beds: '1',
    baths: '1',
    rating: '3',
    notes: 'Studio, but good price',
    link: 'https://www.apartments.com/the-mason-on-chestnut-philadelphia-pa/460g68l/',
    user_id: '1',
    appartment_collection_id: '2'
  },
  {
    address1: '409 E Butler Ave',
    city: 'Doylestown',
    state: 'PA',
    zip: '18901',
    date_added: '2024-01-13 11:30:00',
    rent: '$2155',
    beds: '1',
    baths: '1',
    rating: '3',
    notes: 'Expensive, but closer to work',
    link: 'https://www.apartments.com/butler-square-doylestown-pa/7n9qflz/',
    user_id: '1',
    appartment_collection_id: '2'
  },
  {
    address1: '125 W Farrell Ave',
    city: 'Ewing',
    state: 'NJ',
    zip: '08618',
    date_added: '2024-01-14: 13:33:00',
    rent: '$1715',
    beds: '1',
    baths: '1',
    rating: '2',
    notes: 'Good area, but longer communte',
    link: 'https://www.apartments.com/carlton-ewing-nj/ytl9cyt/',
    user_id: '1',
    appartment_collection_id: '2'
  },
  {
    address1: '957 Bristol Pike',
    city: 'Bensalem',
    state: 'PA',
    zip: '19020',
    date_added: '2024-01-13 15:30:00',
    rent: '$1350',
    beds: '1',
    baths: '1',
    rating: '4',
    notes: 'Nice floor plan',
    link: 'https://www.apartments.com/riverview-crossings-bensalem-pa/8bmf3t0/',
    user_id: '1',
    appartment_collection_id: '2'
  },
  {
    address1: '2555 Old Trevose Rd',
    city: 'Feasterville Trevose',
    state: 'PA',
    zip: '19053',
    date_added: '2024-01-13 16:00:00',
    rent: '$1245',
    beds: '1',
    baths: '1',
    rating: '3',
    notes: 'Pet friendly, but has out dated appliances',
    link: 'https://www.apartments.com/colonial-point-apartments-feasterville-trevose-pa/sd0qgc7/',
    user_id: '1',
    appartment_collection_id: '2'
  },
  {
    address1: '1405 Veterans Hwy',
    city: 'Bristol',
    state: 'PA',
    zip: '19007',
    date_added: '2024-01-14 9:00:00',
    rent: '$1495',
    beds: '1',
    baths: '1',
    rating: '5',
    notes: 'Very modern and great location',
    link: 'https://www.apartments.com/bristol-gardens-apartments-bristol-pa/3n9zhzf/',
    user_id: '1',
    appartment_collection_id: '2'
  },
  
  
];

const seedApartment = () => Apartment.bulkCreate(apartmentData);

module.exports = seedApartment;